<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebApplication1._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="wrapper">
        <div class="game">
            <div class="game-board">
                <table  class="game-board">
                    <tr><td id="a1" class="tw board-tile unused">TW</td>    <td id="a2" class="board-tile unused"></td>         <td id="a3" class="board-tile unused"></td>     <td id="a4" class="d1 board-tile unused">DL</td><td id="a5" class="board-tile unused"></td>     <td id="a6" class="board-tile unused"></td>     <td id="a7" class="board-tile unused"></td>     <td id="a8" class="tw board-tile unused">DL</td>    <td id="a9" class="board-tile unused"></td>     <td id="a10" class="board-tile unused">A10</td>    <td class="board-tile unused">A11</td><td class="d1 board-tile unused">A12</td><td class="board-tile unused">A13</td><td>A14</td><td class="tw board-tile unused">A15</td></tr>
                    <tr><td id="b1" class="board-tile unused"></td>         <td id="b2" class="dw board-tile unused">DW</td>    <td id="b3" class="board-tile unused"></td>     <td id="b4" class="board-tile unused"></td>     <td id="b5" class="board-tile unused"></td>     <td id="b6" class="t1 board-tile unused">TL</td><td id="b7" class="board-tile unused"></td>     <td id="b8" class="board-tile unused"></td>         <td id="b9" class="board-tile unused"></td>     <td id="b10" class="t1 board-tile unused">B10</td><td class="board-tile unused">B11</td><td class="board-tile unused">B12</td><td>B13</td><td class="dw board-tile unused">B14</td><td class="board-tile unused">B15</td></tr>
                    <tr><td id="c1" class="board-tile unused"></td>         <td id="c2" class="board-tile unused"></td>         <td id="c3" class="dw board-tile unused">DW</td><td id="c4" class="board-tile unused"></td>     <td id="c5" class="board-tile unused"></td>     <td id="c6" class="board-tile unused"></td>     <td id="c7" class="d1 board-tile unused">DL</td><td id="c8" class="board-tile unused"></td>         <td id="c9" class="d1 board-tile unused">DL</td><td id="c10" class="board-tile unused">C10</td><td class="board-tile unused">C11</td><td class="board-tile unused">C12</td><td class="dw board-tile unused">C13</td><td class="board-tile unused">C14</td><td class="board-tile unused">C15</td></tr>
                    <tr><td id="d1" class="d1 board-tile unused">DL</td>    <td id="d2" class="board-tile unused"></td>         <td id="d3" class="board-tile unused"></td>     <td id="d4" class="dw board-tile unused">DW</td><td id="d5" class="board-tile unused"></td>     <td id="d6" class="board-tile unused"></td>     <td id="d7" class="board-tile unused"></td>     <td id="d8" class="d1 board-tile unused">DL</td>    <td id="d9" class="board-tile unused"></td>     <td id="d10">D10</td><td class="board-tile unused">D11</td><td class="dw board-tile unused">D12</td><td class="board-tile unused">D13</td><td class="board-tile unused">D14</td><td class="d1 board-tile unused">D15</td></tr>
                    <tr><td id="e1" class="board-tile unused"></td>         <td id="e2" class="board-tile unused"></td>         <td id="e3" class="board-tile unused"></td>     <td id="e4" class="board-tile unused"></td>     <td id="e5" class="dw board-tile unused">DW</td><td id="e6" class="board-tile unused"></td>     <td id="e7" class="board-tile unused"></td>     <td id="e8" class="board-tile unused"></td>         <td id="e9" class="board-tile unused"></td>     <td id="e10" class="board-tile unused">E10</td><td class="dw board-tile unused">E11</td><td class="board-tile unused">E12</td><td class="board-tile unused">E13</td><td class="board-tile unused">E14</td><td class="board-tile unused">E15</td></tr>
                    <tr><td id="f1" class="board-tile unused"></td>         <td id="f2" class="t1 board-tile unused">TL</td>    <td id="f3" class="board-tile unused"></td>     <td id="f4" class="board-tile unused"></td>     <td id="f5" class="board-tile unused"></td>     <td id="f6" class="t1 board-tile unused">TL</td><td id="f7" class="board-tile unused"></td>     <td id="f8" class="board-tile unused"></td>         <td id="f9" class="board-tile unused"></td>     <td id="f10" class="t1 board-tile unused">F10</td><td class="board-tile unused">F11</td><td class="board-tile unused">F12</td><td class="board-tile unused">F13</td><td class="t1 board-tile unused">F14</td><td class="board-tile unused">F15</td></tr>
                    <tr><td id="g1" class="board-tile unused"></td>         <td id="g2" class="board-tile unused"></td>         <td id="g3" class="d1 board-tile unused">DL</td><td id="g4" class="board-tile unused"></td>     <td id="g5" class="board-tile unused"></td>     <td id="g6" class="board-tile unused"></td>     <td id="g7" class="d1 board-tile unused">DL</td><td id="g8" class="board-tile unused"></td>         <td id="g9" class="d1 board-tile unused">DL</td><td id="g10" class="board-tile unused">G10</td><td class="board-tile unused">G11</td><td class="board-tile unused">G12</td><td class="d1 board-tile unused">G13</td><td class="board-tile unused">G14</td><td class="board-tile unused">G15</td></tr>
                    <tr><td id="h1" class="baord-tile unused tw">TW</td>    <td id="h2" class="board-tile unused"></td>         <td id="h3" class="board-tile unused"></td>     <td id="h4" class="d1 board-tile unused">DL</td><td id="h5" class="board-tile unused"></td>     <td id="h6" class="board-tile unused"></td>     <td id="h7" class="board-tile unused"></td>     <td id="h8" class="start board-tile unused">DW</td> <td id="h9" class="board-tile unused"></td>     <td id="h10" class="board-tile unused">H10</td><td class="board-tile unused">H11</td><td class="d1 board-tile unused">H12</td><td class="board-tile unused">H13</td><td class="board-tile unused">H14</td><td class="tw board-tile unused">H15</td></tr>
                    <tr><td id="i1" class="board-tile unused"></td>         <td id="i2" class="board-tile unused"></td>         <td id="i3" class="d1 board-tile unused">DL</td><td id="i4" class="board-tile unused"></td>     <td id="i5" class="board-tile unused"></td>     <td id="i6" class="board-tile unused"></td>     <td id="i7" class="d1 board-tile unused">DL</td><td id="i8" class="board-tile unused"></td>         <td id="i9" class="d1 board-tile unused">DL</td><td id="i10" class="board-tile unused">I10</td><td>I11</td><td>I12</td><td class="d1">I13</td><td>I14</td><td>I15</td></tr>
                    <tr><td id="j1" class="board-tile unused"></td>         <td id="j2" class="t1 board-tile unused">TL</td>    <td id="j3" class="board-tile unused"></td>     <td id="j4" class="board-tile unused"></td>     <td id="j5" class="board-tile unused"></td>     <td id="j6" class="t1 board-tile unused">TL</td><td id="j7" class="board-tile unused"></td>     <td id="j8" class="board-tile unused"></td>         <td id="j9" class="board-tile unused"></td>     <td id="j10" class="t1 board-tile unused">J10</td><td>J11</td><td>J12</td><td>J13</td><td class="t1">J14</td><td>J15</td></tr>
                    <tr><td id="k1" class="board-tile unused"></td>         <td id="k2" class="board-tile unused"></td>         <td id="k3" class="board-tile unused"></td>     <td id="k4" class="board-tile unused"></td>     <td id="k5" class="dw board-tile unused">DW</td><td id="k6" class="board-tile unused"></td>     <td id="k7" class="board-tile unused"></td>     <td id="k8" class="board-tile unused"></td>         <td id="k9" class="board-tile unused"></td>     <td id="k10" class="board-tile unused">K10</td><td class="dw">K11</td><td>K12</td><td>K13</td><td>K14</td><td>K15</td></tr>
                    <tr><td id="l1" class="d1 board-tile unused">DL</td>    <td id="l2" class="board-tile unused"></td>         <td id="l3" class="board-tile unused"></td>     <td id="l4" class="dw board-tile unused">DW</td><td id="l5" class="board-tile unused"></td>     <td id="l6" class="board-tile unused"></td>     <td id="l7" class="board-tile unused"></td>     <td id="l8" class="d1 board-tile unused">DL</td>    <td id="l9" class="board-tile unused"></td>     <td id="l10" class="board-tile unused">L10</td><td>L11</td><td class="dw">L12</td><td>L13</td><td>L14</td><td class="d1">L15</td></tr>
                    <tr><td id="m1" class="board-tile unused"></td>         <td id="m2" class="board-tile unused"></td>         <td id="m3" class="dw board-tile unused">DW</td><td id="m4" class="board-tile unused"></td>     <td id="m5" class="board-tile unused"></td>     <td id="m6" class="board-tile unused"></td>     <td id="m7" class="d1 board-tile unused">DL</td><td id="m8" class="board-tile unused"></td>         <td id="m9" class="d1 board-tile unused">DL</td><td id="m10" class="board-tile unused">M10</td><td>M11</td><td>M12</td><td class="dw">M13</td><td>M14</td><td>M15</td></tr>
                    <tr><td id="n1" class="board-tile unused"></td>         <td id="n2" class="dw board-tile unused">DW</td>    <td id="n3" class="board-tile unused"></td>     <td id="n4" class="board-tile unused"></td>     <td id="n5" class="board-tile unused"></td>     <td id="n6" class="t1 board-tile unused">TL</td><td id="n7" class="board-tile unused"></td>     <td id="n8" class="board-tile unused"></td>         <td id="n9" class="board-tile unused"></td>     <td id="n10" class="t1 board-tile unused">N10</td><td>N11</td><td>N12</td><td>N13</td><td class="dw">N14</td><td>N15</td></tr>
                    <tr><td id="o1" class="tw board-tile unused">TW</td>    <td id="o2" class="board-tile unused"></td>         <td id="o3" class="board-tile unused"></td>     <td id="o4" class="d1 board-tile unused">DL</td><td id="o5" class="board-tile unused"></td>     <td id="o6" class="board-tile unused"></td>     <td id="o7" class="board-tile unused"></td>     <td id="o8" class="tw board-tile unused">TW</td>    <td id="o9" class="board-tile unused"></td>     <td id="o10" class="board-tile unused">O10</td><td>O11</td><td class="d1">O12</td><td>O13</td><td>O14</td><td class="tw">O15</td></tr>
                </table>
            </div>
        </div>
    </div>
    <asp:Button ID="btnSubmit" runat="server" CssClass="btn btn-primary btn-md ml-3" Text="Submit" OnClick="btnSubmit_Click" />
    <asp:Button ID="btnPass" runat="server" CssClass="btn btn-primary btn-md ml-3" Text="Pass" OnClick="btnPass_Click" />
    <div class="score-board">
        <table  id="score-board" class="score-board">
            <tr><th id="r1">Player</th><th id="r1">Score</th></tr>
            <tr><td id="r1">Peter</td> <td id="r1">1000</td></tr>
            <tr><td id="r1">Lois</td><td id="r1">900</td></tr>
        </table>
    </div>
    <asp:Button ID="btnChallenge" runat="server" CssClass="btn btn-primary btn-md ml-3" Text="Challenge" OnClick="btnChallenge_Click"/>
        

</asp:Content>
