//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Scrabble.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserGame
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public int UserId { get; set; }
        public bool IsWinner { get; set; }
        public int PlayerScore { get; set; }
    
        public virtual tblGame tblGame { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
